# Generated by Django 4.2.2 on 2023-06-20 10:06

import django.core.validators
from django.db import migrations, models
import my_plant_app.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(3)])),
                ('first_name', models.CharField(max_length=20, validators=[my_plant_app.web.validators.capital_letter_validation])),
                ('last_name', models.CharField(max_length=20, validators=[my_plant_app.web.validators.capital_letter_validation])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
