# Generated by Django 4.2.2 on 2023-06-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(choices=[('OUTDOOR PLANTS', 'Outdoor Plants'), ('INDOOR PLANTS', 'Indoor Plants')], max_length=14),
        ),
    ]
