from project.aquarium.freshwater_aquarium import FreshwaterAquarium
from project.aquarium.saltwater_aquarium import SaltwaterAquarium
from project.controller import Controller
from project.decoration.plant import Plant
from project.fish.freshwater_fish import FreshwaterFish

c = Controller()
a = FreshwaterAquarium("Fresh Water")
a1 = SaltwaterAquarium("Salt Water")
# print(c.add_aquarium("FreshwaterAquarium", "Fresh Water"))
print(c.add_aquarium("SaltwaterAquarium", "Salt Water"))
d = Plant()
# f = FreshwaterFish("Ivan", "Mura", 100)
print(c.add_decoration("Plant"))
# print(c.decorations_repository.decorations)
print(c.insert_decoration("Fresh Water", "Plant"))
# print(c.decorations_repository.decorations)
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))

print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))
print(c.add_fish("Salt Water", "SaltwaterFish", "Ivann", "Mu1ra", 100))

# print(c.calculate_value("Salt Water"))
# print(c.report())